Traceback (most recent call last):
  File "/home/grabow/anaconda3/envs/jb/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/grabow/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/grabow/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/grabow/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/grabow/anaconda3/envs/jb/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/grabow/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/grabow/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/grabow/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# computation of C
def head0(z, UL=UL, UR=UR, H=H, d=d):
    zeta = 0 + z * 1j
    tau = taufunc(zeta, H=H, d=d)
    return omegafunc(tau, UL=UL, UR=UR, H=H, d=d).real / np.sqrt(kx * kz)

from scipy.integrate import quad
h0avg = quad(head0, a=-H, b=0, args=(UL, UR))[0] / H
C = (UL - UR) / (h0avg - 0)
print(f'Effective conducatance: C={C:.2f} m^2/d')
print(f'Dupuit head h0={h0avg:.3f} m for UL={UL} m^2/d and UR={UR} m^2/d')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [14][0m, in [0;36m<cell line: 7>[0;34m()[0m
[1;32m      4[0m     tau [38;5;241m=[39m taufunc(zeta, H[38;5;241m=[39mH, d[38;5;241m=[39md)
[1;32m      5[0m     [38;5;28;01mreturn[39;00m omegafunc(tau, UL[38;5;241m=[39mUL, UR[38;5;241m=[39mUR, H[38;5;241m=[39mH, d[38;5;241m=[39md)[38;5;241m.[39mreal [38;5;241m/[39m np[38;5;241m.[39msqrt(kx [38;5;241m*[39m kz)
[0;32m----> 7[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mintegrate[39;00m [38;5;28;01mimport[39;00m quad
[1;32m      8[0m h0avg [38;5;241m=[39m quad(head0, a[38;5;241m=[39m[38;5;241m-[39mH, b[38;5;241m=[39m[38;5;241m0[39m, args[38;5;241m=[39m(UL, UR))[[38;5;241m0[39m] [38;5;241m/[39m H
[1;32m      9[0m C [38;5;241m=[39m (UL [38;5;241m-[39m UR) [38;5;241m/[39m (h0avg [38;5;241m-[39m [38;5;241m0[39m)

[0;31mModuleNotFoundError[0m: No module named 'scipy'
ModuleNotFoundError: No module named 'scipy'

